version: "3.8"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/media/appdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
        - /home/media/appdata/mosquitto:/mosquitto
    ports:
        - '1883:1883'
        - '9001:9001'
    command: 'mosquitto -c /mosquitto-no-auth.conf'

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /home/media/appdata/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

# volumes:
#   influxdb-storage:
#   chronograf-storage:
#   grafana-storage:
