version: "2.4"

services:
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:ubuntu
    restart: always
    network_mode: host
    environment:
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8222
      - TZ=America/Los_Angeles
    volumes:
      - /home/media/appdata/homebridge:/homebridge
  scrypted:
    image: koush/scrypted:latest
    container_name: scrypted
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/media/appdata/scrypted:/server/volume/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/media/appdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
