version: "3.8"

# Reference: http://mroach.com/2020/08/pi-hole-and-cloudflared-with-docker/#option-2-attach-cloudflared-to-the-lan

services:
  tailscale:
    container_name: tailscale
    restart: unless-stopped
    privileged: true
    image: ido1990/tailscale-docker
    environment:
      - "AUTHKEY=${TAILSCALEAUTHKEY}"
      - "ROUTES=10.1.1.0/24"
    networks:
      private_lan:
        ipv4_address: 10.1.1.4

  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    hostname: 10.1.1.2
    domainname: pihole.local
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      - FTLCONF_LOCAL_IPV4=10.1.1.2
      - TZ=America/Los_Angeles
      - WEBTHEME="default-auto"
      - REV_SERVER="false"
      - REV_SERVER_TARGET="false"
      - REV_SERVER_DOMAIN="local"
      - REV_SERVER_CIDR=10.0.0.0/8
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    networks:
      private_lan:
        ipv4_address: 10.1.1.2
    restart: unless-stopped

networks:
  # Create the internal network
  internal:
    ipam:
      config:
        - subnet: 172.30.9.0/29

  # The priv_lan network is already setup, so it is an 'external' network
  private_lan:
    external:
      name: private_lan

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:
